## Week 1 Prep - pandas series and data frames

## Importing `pandas` and `numpy`

In [3]:
import pandas as pd
import numpy as np

## Series

#### Comparing a numpy array to a pandas series

In [4]:
# A numpy array
arr = np.random.randn(4) # random values from std normal distribution
print(type(arr))
print(arr, "\n")

# A pandas series made from the previous array
s = pd.Series(arr)
print(type(s))
print(s)

<class 'numpy.ndarray'>
[-0.42332403  0.94184511  0.20014872  1.87952355]

<class 'pandas.core.series.Series'>
0   -0.423324
1    0.941845
2    0.200149
3    1.879524
dtype: float64

### Creating a `pandas.Series`

In [5]:
#s = pd.Series(data, index=index)

The `data` parameter can be:
- a list or NumPy array,
- a Python dictionary, or
- a single number, boolean (`True/False`), or string.

The `index` parameter is optional.

Example: Creating a `pandas.Series` from a NumPy array

In [6]:
# A series from a numpy array (as the data parameter)
pd.Series(np.arange(3), index=[2023, 2024, 2025])

2023    0
2024    1
2025    2
dtype: int64

Example: Creating a `pandas.Series` from a list

In [7]:
# A series from a list of strings with default index
pd.Series(['EDS 220', 'EDS 222', 'EDS 223', 'EDS 242'])

0    EDS 220
1    EDS 222
2    EDS 223
3    EDS 242
dtype: object

Example: Creating a `pandas.Series` from a dictionary

If we create a pandas.Series via a dictionary the keys will become the index and the values the corresponding data.

In [8]:
# Construct dictionary
d = {'key_0':2, 'key_1':'3', 'key_2':5}

# Initialize series using a dictionary
pd.Series(d)

key_0    2
key_1    3
key_2    5
dtype: object

Example: Creating a `pandas.Series` from a single value

If we only provide a single number, boolean, or string as the data for the series, we need to provide an index. The value will be repeated to match the length of the index. Here, we create a series from a single float number with an index given by a list of strings:

In [9]:
pd.Series(3.0, index = ['A', 'B', 'C'])

A    3.0
B    3.0
C    3.0
dtype: float64

### Simple Operations

Arithmetic operations work on series and so do most NumPy functions. For example:

In [10]:
# Define a series
s = pd.Series([98,73,65],index=['Andrea', 'Beth', 'Carolina'])

# Divide each element in series by 10
print(s /10, '\n')

# Take the exponential of each element in series
print(np.exp(s), '\n')

# Original series is unchanged
print(s)

Andrea      9.8
Beth        7.3
Carolina    6.5
dtype: float64

Andrea      3.637971e+42
Beth        5.052394e+31
Carolina    1.694889e+28
dtype: float64

Andrea      98
Beth        73
Carolina    65
dtype: int64

We can also produce new pandas.Series with True/False values indicating whether the elements in a series satisfy a condition or not:

In [11]:
s > 70

Andrea       True
Beth         True
Carolina    False
dtype: bool

This kind of simple conditions on pandas.Series will be key when we are selecting data from data frames.

### Identifying missing values

In pandas we can represent a missing, NULL, or NA value with the float value numpy.nan, which stands for “not a number”. Let’s construct a small series with some NA values represented this way:

In [12]:
# Series with NAs in it
s = pd.Series([1, 2, np.nan, 4, np.nan])
s

0    1.0
1    2.0
2    NaN
3    4.0
4    NaN
dtype: float64

Notice the data type of the values in the series is still float64.

The `hasnans` attribute for a pandas.Series returns True if there are any NA values in it and False otherwise:

In [13]:
# Check if series has NAs
s.hasnans

True

After detecting there are NA values, we might be interested in knowing which elements in the series are NAs. We can do this using the `isna` method:

In [14]:
s.isna()

0    False
1    False
2     True
3    False
4     True
dtype: bool

The output is a `pandas.Series` of boolean values indicating if an element in the row at the given index is `np.nan` (`True` = is NA) or not (`False`= not NA).

#### Check in #1

The integer number -999 is often used to represent missing values. Create a `pandas.Series` named `s` with four integer values, two of which are -999. The index of this series should be the letters A through D.

In [27]:
# Dictionary of integer values with an index of letters A through D
dict_ints = {'A': -999, 'B': 11, 'C': 24, 'D': -999}

# Creating a pandas.Series using a dictionary
s = pd.Series(dict_ints)

s

A   -999
B     11
C     24
D   -999
dtype: int64

#### Check in #2

In the `pandas.Series` documentation, look for the method `mask()`. Use this method to update the series s so that the -999 values are replaced by NA values. HINT: check the first example in the method’s documentation.

In [19]:
# Replacing -999 values with NA values
s = s.mask(s == -999)
s

A     NaN
B    11.0
C    24.0
D     NaN
dtype: float64

## Data Frames

The `pandas.DataFrame` is the most used pandas object. It represents tabular data and we can think of it as a spreadsheet. Each column of a `pandas.DataFrame` is a `pandas.Series`.

### Creating a `pandas.DataFrame`

We already mentioned each column of a `pandas.DataFrame` is a `pandas.Series`. In fact, the `pandas.DataFrame` is a dictionary of `pandas.Series`, with each column name being the key and the column values being the key’s value. Thus, we can create a `pandas.DataFrame` in this way:

In [20]:
# Initialize dictionary with columns' data 
d = {'col_name_1' : pd.Series(np.arange(3)),
     'col_name_2' : pd.Series([3.1, 3.2, 3.3]),
     }

# Create data frame
df = pd.DataFrame(d)
df

   col_name_1  col_name_2
0           0         3.1
1           1         3.2
2           2         3.3

We can change the `index` by changing the index attribute in the data frame:

In [21]:
# Change index
df.index = ['a','b','c']
df

   col_name_1  col_name_2
a           0         3.1
b           1         3.2
c           2         3.3

#### Check in #3

We can access the data frame’s column names via the `columns` attribute. Update the column names to C1 and C2 by updating this attribute.

In [26]:
# Updating the column names of the df
df.columns = ['C1', 'C2']
df

   C1   C2
a   0  3.1
b   1  3.2
c   2  3.3